apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabel }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.selectorLabel }}
spec:
    type: {{ .Values.service.type }}
    selector:
        app: {{ .Values.selectorLabel }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: 3000
