# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build pnpm and push to ACR

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 100
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.14.6

    - name: Install Dependencies
      run: pnpm install

    - name: Run Linter
      run: pnpm run lint --filter @eratos/app

  build:
    runs-on: ubuntu-latest
    needs: linter
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: eratos.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build the Docker image and push to ACR
      run: |
        docker build -t eratos.azurecr.io/monorepo-test-ci:${{ github.sha }} .
        docker push eratos.azurecr.io/monorepo-test-ci:${{ github.sha }}

